// Listado de materias disponibles para los cursos. El primer elemento es el
// placeholder del <select> (no es una materia válida).
export const materiaOpc = [
    "Seleccione una materia",
    "Precálculo",
    "Elementos para el estudio de la ciencia y la tecnología",
    "Matemática discreta I",
    "Fundamentos de programación",
    "Álgebra vectorial y matrices",
    "Cálculo I",
    "Programación de estructuras dinámicas",
    "Matemática discreta II",
    "Física I",
    "Cálculo II",
    "Programación orientada a objetos",
    "Bases de datos",
    "Electricidad y magnetismo",
    "Cálculo III",
    "Programación web",
    "Administración de bases de datos",
    "Optativa humanístico-social I",
    "Análisis numérico",
    "Redes de computadoras",
    "Programación de dispositivos móviles",
    "Análisis de sistemas",
    "Física II",
    "Optativa humanístico-social II",
    "Análisis de algoritmos",
    "Programación de artefactos",
    "Probabilidad y estadística",
    "Seguridad en entornos de desarrollo",
    "Arquitectura de computadoras",
    "Técnicas de simulación de computadoras",
    "Programación N-capas",
    "Fundamentos de inteligencia de negocios",
    "Optativa humanístico-social III",
    "Sistemas operativos",
    "Programación declarativa",
    "Ingeniería de software",
    "Formulación y evaluación de proyectos",
    "Optativa humanístico-social IV",
    "Optativa técnica I",
    "Aplicaciones código abierto",
    "Práctica profesional I",
    "Optativa técnica II",
    "Teoría de lenguaje de programación",
    "Optativa humanístico-social V",
    "Práctica profesional II",
];
